### PR TITLE
Update Backstories.xml

### PR DESCRIPTION
**Pull request by Annohorium**
Don't own the game but would like to help the project.

### CODE REVIEW

**Comment by Elevator89** [comment]
Thank you for your work, but we already have a [pull-request](#425) that covers most of changes you have made. Feel free to participate the discussion.
Generally, we have a lot of work to do, and any help will be appreciated. You may start from looking at our [issue list](https://github.com/Ludeon/RimWorld-ru/issues) and take one of them. For example, [this one](https://github.com/Ludeon/RimWorld-ru/issues/406) contains "Geologist2" backstory that you've translated in your request. 
But if you don't want to do big tasks you may create the other pull-request that contains only "Geologist2" story, and we'll review and merge it soon.
If you don't want to do any more translations, we'll consider merging this particular request only after the [existing one](#425) is merged.

**Comment by Elevator89** [comment]
А вообще, мы по-русски общаемся.

**Comment by Annohorium** [comment]
Ёлки палки, я в первый раз попытался сделать подобное))

**Comment by Elevator89** [comment]
Не могу смержить, к сожалению. С литературной точки зрения имеющийся перевод выглядит не хуже представленного.
Чтобы в дальнейшем не пересекаться с уже готовым переводом, советую взять себе ишью и делать именно её.

**Pull request closed without merging**
